Update iOS-StoreSubmit.yaml

diff --git a/iOS-StoreSubmit.yaml b/iOS-StoreSubmit.yaml
--- a/iOS-StoreSubmit.yaml
+++ b/iOS-StoreSubmit.yaml
@@ -33,38 +33,96 @@ steps:
       export LANGUAGE=en_US.UTF-8
       locale
       curl -o ./$IPAFileName -k $IPAFileUrl
-      bundle init
-      echo "gem \"fastlane\"">>Gemfile
-      mkdir fastlane
-      touch fastlane/Appfile
-      touch fastlane/Fastfile
-      mv $FastFileConfig fastlane/Fastfile
-      #cat fastlane/Fastfile
-      mv $AppStoreConnectApiKey $AppStoreConnectApiKeyFileName
-      #cat $AppStoreConnectApiKeyFileName
-      
-      if [ $StackType == 10 ]
+          
+      if [ $appleStoreSubmitApiType == 0 ]   #ApplicationSpecificPasswordConnection
       then
-      	bundle exec fastlane doTestFlight #--verbose
-        if [ $? -eq 0 ]
+      
+        mkdir filename.itmsp
+
+        cp ./$IPAFileName filename.itmsp/$IPAFileName
+
+        fileSize=` stat -f %z $IPAFileName`
+        md5Checksum=`find -s filename.itmsp/ -type f -exec md5 -q {} \; | md5`
+        bundleIdentifier=$BundleId
+        appleId="$AppleId"
+
+        dir="/usr/local/itms/bin/"
+
+        echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" > filename.itmsp/metadata.xml
+        echo "<package xmlns=\"http://apple.com/itunes/importer\" version=\"software5.4\">" >> filename.itmsp/metadata.xml
+        echo "    <software_assets bundle_identifier=\"$bundleIdentifier\" apple_id=\"$appleId\" app_platform=\"ios\">" >> filename.itmsp/metadata.xml
+        echo "        <asset type=\"bundle\">" >> filename.itmsp/metadata.xml 
+        echo "        	<data_file>" >> filename.itmsp/metadata.xml
+        echo "                <size>$fileSize</size>" >> filename.itmsp/metadata.xml 
+        echo "                <file_name>$IPAFileName</file_name>" >> filename.itmsp/metadata.xml 
+        echo "            	  <checksum type=\"md5\">$md5Checksum</checksum>" >> filename.itmsp/metadata.xml
+        echo "          </data_file>" >> filename.itmsp/metadata.xml 
+        echo "        </asset>" >> filename.itmsp/metadata.xml
+        echo "    </software_assets>" >> filename.itmsp/metadata.xml 
+        echo "</package>" >> filename.itmsp/metadata.xml
+        
+        if [ $StackType == 10 ] #TestFlight
         then
-          echo "TestFlight progress succeeded"
-          exit 0
-        else
-          echo "TestFlight progress failed :" >&2
-          exit 1
+          $dir/iTMSTransporter -m transferTest -u '$AppleUserName' -p '$ApplicationSpecificPassword' -f "./filename.itmsp" -k 100000
+          
+          if [ $? -eq 0 ]
+          then
+            echo "TestFlight progress succeeded"
+            exit 0
+          else
+            echo "TestFlight progress failed :" >&2
+            exit 1
+          fi
+        fi
+        if [ $StackType == 12 ] #Release
+        then
+          $dir/iTMSTransporter -m upload -u '$AppleUserName' -p '$ApplicationSpecificPassword' -f "./filename.itmsp" -k 100000
+          if [ $? -eq 0 ] 
+          then
+            echo "Release progress succeeded"
+            exit 0
+          else
+            echo "Release progress failed :" >&2
+            exit 1
+          fi
         fi
       fi
-      if [ $StackType == 12 ]
+      
+      if [ $appleStoreSubmitApiType == 1 ]   #AppStoreConnectApiConnection
       then
-      	bundle exec fastlane doRelease #--verbose
-        if [ $? -eq 0 ] 
+        bundle init
+        echo "gem \"fastlane\"">>Gemfile
+        mkdir fastlane
+        touch fastlane/Appfile
+        touch fastlane/Fastfile
+        mv $FastFileConfig 'fastlane/Fastfile
+        #cat fastlane/Fastfile
+        mv '$AppStoreConnectApiKey' '$AppStoreConnectApiKeyFileName'
+        #cat $AppStoreConnectApiKeyFileName
+
+        if [ $StackType == 10 ]
         then
-          echo "Release progress succeeded"
-          exit 0
-        else
-          echo "Release progress failed :" >&2
-          exit 1
+          bundle exec fastlane doTestFlight #--verbose
+          if [ $? -eq 0 ]
+          then
+            echo "TestFlight progress succeeded"
+            exit 0
+          else
+            echo "TestFlight progress failed :" >&2
+            exit 1
+          fi
+        fi
+        if [ $StackType == 12 ]
+        then
+          bundle exec fastlane doRelease #--verbose
+          if [ $? -eq 0 ] 
+          then
+            echo "Release progress succeeded"
+            exit 0
+          else
+            echo "Release progress failed :" >&2
+            exit 1
+          fi
         fi
       fi
       echo "11"
