Update iOS-StoreSubmit.yaml

diff --git a/iOS-StoreSubmit.yaml b/iOS-StoreSubmit.yaml
--- a/iOS-StoreSubmit.yaml
+++ b/iOS-StoreSubmit.yaml
@@ -3,6 +3,19 @@ directories:
 - AC_SOURCE
 - AC_OUTPUT_DIR
 steps:
+- componentType: appcircle_xcode_select
+  componentVersion: "1.0.*"
+  stepName: Xcode Select
+  enabled: true
+  onError: $exit
+  webUrl: https://github.com/appcircleio/appcircle-xcode-select-component
+  repoUrl: https://github.com/appcircleio/appcircle-xcode-select-component.git
+  commit: 79e4266
+  inputs:
+  - AC_XCODE_LIST_DIR: "$AC_XCODE_LIST_DIR"
+  - AC_XCODE_VERSION: "11.5.x"
+  outputs:
+  - XCODE_DEVELOPER_DIR_PATH: "XCODE_DEVELOPER_DIR_PATH"
 - componentType: appcircle_custom_script
   componentVersion: "1.0.*"
   stepName: Custom Script
@@ -14,40 +27,44 @@ steps:
   inputs:
   - Execute: "bash"
   - Script: |
-      echo "1"
-      sudo gem install fastlane -NV
-      echo "2"
-      sudo gem install bundler
-      
+      echo "0"
+      export LC_ALL=en_US.UTF-8
+      export LANG=en_US.UTF-8
+      export LANGUAGE=en_US.UTF-8
+      locale
       curl -o ./$IPAFileName -k $IPAFileUrl
-      echo "3"
       bundle init
-      echo "4"
       echo "gem \"fastlane\"">>Gemfile
-      echo "5"
       mkdir fastlane
-      echo "6"
       touch fastlane/Appfile
-      echo "7"
       touch fastlane/Fastfile
-      echo "8"
       mv $FastFileConfig fastlane/Fastfile
-      echo "8-2"
-      cat fastlane/Fastfile
-      echo "9"
+      #cat fastlane/Fastfile
       mv $AppStoreConnectApiKey $AppStoreConnectApiKeyFileName
-      echo "9-2"
-      cat $AppStoreConnectApiKeyFileName
-      echo "10"
-      fastlane env
-      echo 10-2
+      #cat $AppStoreConnectApiKeyFileName
       
       if [ $StackType == 10 ]
       then
-      	bundle exec fastlane TestFlight
+      	bundle exec fastlane doTestFlight #--verbose
+        if [ $? -eq 0 ]
+        then
+          echo "TestFlight progress succeeded"
+          exit 0
+        else
+          echo "TestFlight progress failed :" >&2
+          exit 1
+        fi
       fi
       if [ $StackType == 12 ]
       then
-      	bundle exec fastlane Release
+      	bundle exec fastlane doRelease #--verbose
+        if [ $? -eq 0 ] 
+        then
+          echo "Release progress succeeded"
+          exit 0
+        else
+          echo "Release progress failed :" >&2
+          exit 1
+        fi
       fi
       echo "11"
